# cbpro_tickers = ['BAND-BTC', 'ACH-USDT', 'MASK-EUR', 'AERGO-USD', 'BNT-USD', 'BTC-USDC', 'API3-USDT', 'CHZ-USD',
#                  'ELA-USD', 'RLY-EUR', 'FIL-USD', 'ERN-EUR', 'ICP-BTC', 'LOOM-USDC', 'ARKM-USD', 'FORTH-GBP', 'DNT-USD',
#                  'MINA-USD', 'NEST-USDT', 'BICO-USD', 'WBTC-USD', 'OP-USDT', 'CRV-GBP', 'CVC-USD', 'RPL-USD',
#                  'KEEP-USD', 'XRP-USDT', 'BADGER-USDT', 'CVX-USD', 'SHPING-EUR', 'OSMO-USD', 'TVK-USD', 'NU-BTC',
#                  'GODS-USD', 'USDT-USDC', 'DIMO-USD', 'BLUR-USD', 'QUICK-USD', 'RAD-BTC', 'BOBA-USDT', 'BTC-USDT',
#                  'QSP-USDT', 'GALA-USDT', 'OGN-BTC', 'GRT-GBP', 'SUSHI-EUR', 'BADGER-USD', 'NKN-EUR', 'CLV-USD',
#                  'HFT-USD', 'MATIC-EUR', 'FLOW-USD', 'BAL-BTC', 'SPA-USD', 'MINA-EUR', 'REQ-BTC', 'WLUNA-GBP', 'NU-USD',
#                  'ANT-USD', 'RAD-EUR', 'STORJ-USD', 'MIR-EUR', 'YFII-USD', 'ETH-USD', 'DAI-USD', 'GNO-USD', 'ASM-USD',
#                  'SHIB-USD', 'AERO-USD', 'BIGTIME-USD', 'HOPR-USD', 'QNT-USDT', 'LOKA-USD', 'KRL-USDT', 'QSP-USD',
#                  'ATA-USD', 'ALCX-EUR', 'RLC-BTC', 'ALEPH-USD', 'RARE-USD', 'KSM-USDT', 'MXC-USD', 'WCFG-EUR',
#                  'ALGO-EUR', '1INCH-GBP', 'SNX-BTC', 'USDC-GBP', 'XYO-BTC', 'USDC-EUR', 'RENDER-USD', 'JASMY-USD',
#                  'RLY-GBP', 'MKR-USD', 'COTI-USD', '1INCH-USD', 'TRB-USD', 'IDEX-USDT', 'ALGO-BTC', 'GALA-USD',
#                  'NKN-USD', 'DIA-USDT', 'XCN-USD', 'SYN-USD', 'RLY-USD', 'KARRAT-USD', 'XTZ-BTC', 'BAT-EUR', 'DOGE-BTC',
#                  'ALGO-USD', 'SAND-USD', 'BOBA-USD', 'GAL-USDT', 'SHIB-EUR', 'TRU-USDT', '00-USD', 'FIS-USDT',
#                  'WCFG-USD', 'SKL-BTC', 'WLUNA-USDT', 'DOGE-EUR', 'ADA-USD', 'ATOM-GBP', 'NKN-BTC', 'ZETA-USD',
#                  'BTRST-EUR', 'UNI-GBP', 'FIL-EUR', 'SUKU-USDT', 'AUCTION-EUR', 'NEST-USD', 'SYLO-USD', 'FIDA-EUR',
#                  'PRQ-USD', 'AXS-EUR', 'LINK-USD', 'UMA-GBP', 'REN-BTC', 'REQ-GBP', 'ETH-DAI', 'XCN-USDT', 'INDEX-USDT',
#                  'XRP-USD', 'XTZ-GBP', 'ORN-BTC', 'LTC-GBP', 'VTHO-USD', 'SOL-GBP', 'TRAC-USDT', 'DOGE-USDT',
#                  'COMP-BTC', 'AIOZ-USD', 'RARI-USD', 'CRPT-USD', 'DOT-USDT', 'DESO-EUR', 'SOL-EUR', 'CBETH-USD',
#                  'STORJ-BTC', 'APE-EUR', 'UNI-USD', 'GYEN-USD', 'ETH-USDC', 'EOS-BTC', 'DDX-USDT', 'ENS-EUR',
#                  'POWR-EUR', 'GALA-EUR', 'REQ-USDT', 'DNT-USDC', 'UMA-USD', 'LTC-EUR', 'TRAC-USD', 'HBAR-USDT',
#                  'ZRX-USD', 'DYP-USD', 'CRO-EUR', 'XRP-EUR', 'AVAX-USDT', 'AUDIO-USD', 'UST-USD', 'BTRST-GBP',
#                  'POLY-USDT', 'TNSR-USD', 'XTZ-EUR', 'OOKI-USD', 'REP-BTC', 'ICP-USD', 'SUSHI-ETH', 'RAD-USDT',
#                  'FIS-USD', 'MULTI-USD', 'CRO-USDT', 'KNC-BTC', 'INJ-USD', 'LINK-USDT', 'BCH-GBP', 'QI-USD', 'RLC-USD',
#                  'DASH-USD', 'BONK-USD', 'REN-USD', 'ZEC-USDC', 'APT-USD', 'XLM-USD', 'BTRST-USD', 'ORN-USD', 'SNX-EUR',
#                  'FIDA-USDT', 'POND-USD', 'TONE-USD', 'FORT-USD', 'VOXEL-USD', 'EUROC-USD', 'GST-USD', 'MATIC-USD',
#                  'METIS-USD', 'DESO-USD', 'OXT-USD', 'POLS-USDT', 'OGN-USD', 'BTC-GBP', 'NMR-BTC', 'AXS-USDT',
#                  'ANKR-EUR', 'XYO-USDT', 'HIGH-USD', 'GNO-USDT', 'DOGE-GBP', 'HONEY-USD', 'TRU-USD', 'BAT-BTC',
#                  'CRV-EUR', 'TRB-BTC', 'SHDW-USD', 'C98-USD', 'OMG-GBP', 'CELR-USD', 'ALGO-GBP', 'ETC-USD', 'MAGIC-USD',
#                  'SPELL-USD', 'YFI-USD', 'REP-USD', 'LSETH-USD', 'DOT-USD', 'BTRST-USDT', 'EOS-USD', 'BAND-USD',
#                  'QNT-USD', 'DOT-EUR', 'T-USD', 'ACS-USD', 'AAVE-EUR', 'GFI-USD', 'VGX-USDT', 'ATOM-EUR', 'ARPA-USD',
#                  'VET-USD', 'STRK-USD', 'MUSD-USD', 'MIR-BTC', 'OMG-BTC', 'TRU-BTC', 'FLOW-USDT', 'CGLD-EUR',
#                  'SOL-ETH', 'MIR-USD', 'HOPR-USDT', 'PERP-USD', 'LCX-EUR', 'MPL-USD', 'BAT-USDC', 'SUSHI-GBP',
#                  'EOS-EUR', 'SYLO-USDT', 'MKR-BTC', 'MSOL-USD', 'KAVA-USD', 'SUSHI-USD', 'DEXT-USD', 'DYP-USDT',
#                  'ARB-USD', 'METIS-USDT', 'LCX-USD', 'MDT-USD', 'HBAR-USD', 'ARPA-EUR', 'TIME-USDT', 'FIDA-USD',
#                  'BNT-BTC', 'NMR-GBP', 'CTX-EUR', 'MEDIA-USDT', 'LRC-BTC', 'GMT-USDT', 'BICO-EUR', 'ARPA-USDT',
#                  'ZRX-BTC', 'APT-USDT', 'FARM-USDT', 'ROSE-USD', 'KRL-USD', 'CGLD-GBP', 'JTO-USD', 'STX-USD', 'CRV-USD',
#                  'FOX-USDT', 'CHZ-EUR', 'MATIC-GBP', 'NMR-EUR', 'JASMY-USDT', 'LIT-USD', 'SEAM-USD', 'AUCTION-USDT',
#                  'COMP-USD', 'NCT-USDT', 'AKT-USD', 'SAND-USDT', 'NCT-EUR', 'POWR-USD', 'INV-USD', 'MOBILE-USD',
#                  'SOL-USD', 'MCO2-USD', 'UPI-USD', 'BLZ-USD', 'DIA-EUR', 'CBETH-ETH', 'SOL-BTC', 'ETH-BTC', 'AIOZ-USDT',
#                  'LRC-USDT', 'PYUSD-USD', 'USDT-EUR', 'BOND-USDT', 'C98-USDT', 'FARM-USD', 'PYR-USD', 'MANA-EUR',
#                  'ATOM-USD', '1INCH-BTC', 'LDO-USD', 'WAMPL-USDT', 'MCO2-USDT', 'TIA-USD', 'NCT-USD', 'RGT-USD',
#                  'IMX-USDT', 'CLV-GBP', 'LRC-USD', 'ATOM-BTC', 'TRIBE-USD', 'REQ-EUR', 'GRT-BTC', 'LINK-GBP',
#                  'COVAL-USD', 'LQTY-USDT', 'PUNDIX-USD', 'GRT-USD', 'RAD-USD', 'MINA-USDT', 'MASK-USD', 'SUKU-EUR',
#                  'PERP-USDT', 'CLV-USDT', 'SNX-USD', 'XRP-BTC', 'MANA-USD', 'LQTY-USD', 'PRO-USD', 'LPT-USD',
#                  'ALCX-USD', 'TRAC-EUR', 'SUI-USD', 'AVAX-USD', 'AVT-USD', 'ENS-USD', 'MASK-USDT', 'PLA-USD',
#                  'MATIC-USDT', 'XRP-GBP', 'MLN-USD', 'SEI-USD', 'WLUNA-EUR', 'LINK-EUR', 'ADA-BTC', 'ONDO-USD',
#                  'EGLD-USD', 'CGLD-BTC', 'SHPING-USD', 'SOL-USDT', 'SNT-USD', 'SKL-GBP', 'AMP-USD', 'ADA-EUR',
#                  'POND-USDT', 'ENJ-BTC', 'WBTC-BTC', 'ZRX-EUR', 'WAXL-USD', 'NMR-USD', 'FET-USD', 'GHST-USD',
#                  'VELO-USD', 'MTL-USD', 'STG-USD', 'LINK-ETH', 'ROSE-USDT', 'DDX-EUR', 'OMNI-USD', 'XLM-USDT',
#                  'CHZ-USDT', 'CTSI-USD', 'LOOM-USD', 'ADA-USDC', 'MUSE-USD', 'ANKR-GBP', 'HNT-USD', 'SUPER-USD',
#                  'AXS-USD', 'MIR-GBP', 'AAVE-USD', 'KRL-EUR', 'USDT-GBP', 'ADA-ETH', 'FORT-USDT', 'XYO-EUR', 'ABT-USD',
#                  'ADA-GBP', 'EUROC-EUR', 'GTC-USD', 'BAND-EUR', 'ETC-BTC', 'RAI-USD', 'UMA-BTC', 'AURORA-USD',
#                  'UNI-EUR', 'BTC-USD', 'FIL-BTC', 'WAMPL-USD', 'ETC-EUR', 'UST-USDT', 'RBN-USD', 'VARA-USD', 'REQ-USD',
#                  'MDT-USDT', 'KSM-USD', 'XTZ-USD', 'FLR-USD', 'SHIB-GBP', 'PERP-EUR', 'PAX-USDT', 'BICO-USDT',
#                  'NEAR-USDT', 'XLM-BTC', 'LQTY-EUR', 'DREP-USD', 'ETH-USDT', 'XYO-USD', 'ENJ-USDT', 'BAT-USD',
#                  'DOGE-USD', 'MANA-ETH', 'BOND-USD', 'AAVE-GBP', 'FOX-USD', 'AAVE-BTC', 'PRIME-USD', 'ALCX-USDT',
#                  'MATIC-BTC', 'IDEX-USD', 'DESO-USDT', 'UNFI-USD', 'GRT-EUR', 'MEDIA-USD', 'DOT-BTC', 'PLU-USD',
#                  'WCFG-USDT', 'ATOM-USDT', 'TIME-USD', 'ILV-USD', 'LTC-BTC', 'SAFE-USD', 'ATA-USDT', 'IMX-USD',
#                  'MASK-GBP', 'ENJ-USD', 'STX-USDT', 'POLS-USD', 'YFI-BTC', 'ETH-EUR', 'RLY-USDT', 'SHPING-USDT',
#                  'AUCTION-USD', 'CTSI-BTC', 'MANA-BTC', 'BAT-ETH', 'SKL-USD', 'ASM-USDT', 'AXL-USD', 'BCH-BTC',
#                  'FORTH-BTC', 'CHZ-GBP', 'POWR-USDT', 'COVAL-USDT', 'IOTX-EUR', 'RNDR-USD', 'PNG-USD', 'AVAX-BTC',
#                  'NEON-USD', 'ETC-GBP', 'BUSD-USD', 'USDT-USD', 'UNI-BTC', 'LSETH-ETH', 'CRO-USD', '1INCH-EUR',
#                  'RNDR-EUR', 'ADA-USDT', 'RONIN-USD', 'ZEC-USD', 'HFT-USDT', 'API3-USD', 'CTX-USDT', 'ICP-EUR',
#                  'BTRST-BTC', 'UPI-USDT', 'DREP-USDT', 'ICP-GBP', 'GNT-USDC', 'APE-USDT', 'CRV-BTC', 'ERN-USD',
#                  'DAI-USDC', 'ANKR-BTC', 'BIT-USD', 'AGLD-USD', 'GLM-USD', 'RNDR-USDT', 'TRU-EUR', 'FORTH-EUR',
#                  'INDEX-USD', 'NKN-GBP', 'DDX-USD', 'PAX-USD', 'FET-USDT', 'CLV-EUR', 'DASH-BTC', 'BNT-EUR', 'DAR-USD',
#                  'ZEC-BTC', 'PRQ-USDT', 'ACH-USD', 'CGLD-USD', 'MATH-USD', 'SPELL-USDT', 'ZEN-USDT', 'ERN-USDT',
#                  'ORN-USDT', 'SNX-GBP', 'GUSD-USD', 'OP-USD', 'VGX-USD', 'AST-USD', 'BAL-USD', 'BIT-USDT', 'AVAX-EUR',
#                  'STG-USDT', 'CVC-USDC', 'BAND-GBP', 'LCX-USDT', 'OCEAN-USD', 'UMA-EUR', 'SUPER-USDT', 'UST-EUR',
#                  'ANKR-USD', 'MATH-USDT', 'SUKU-USD', 'GMT-USD', 'SKL-EUR', 'ALICE-USD', 'OMG-EUR', 'XLM-EUR',
#                  'JUP-USD', 'NEAR-USD', 'ZEN-BTC', 'POLY-USD', 'ELA-USDT', 'IOTX-USD', 'SHIB-USDT', 'OMG-USD',
#                  'MANA-USDC', 'NU-EUR', 'MONA-USD', 'BCH-USD', 'KNC-USD', 'VGX-EUR', 'FIL-GBP', 'DIA-USD', 'LINK-BTC',
#                  'AGLD-USDT', 'BTC-EUR', 'AXS-BTC', 'DOT-GBP', 'SUSHI-BTC', 'BNT-GBP', 'FORTH-USD', 'MNDE-USD',
#                  'BADGER-EUR', 'ORCA-USD', 'ICP-USDT', 'ETH-GBP', 'LTC-USD', 'RAD-GBP', 'WLUNA-USD', 'ENS-USDT',
#                  'NU-GBP', 'CTX-USD', 'BCH-EUR', 'FX-USD', 'ZEN-USD', 'SWFTC-USD', 'WCFG-BTC', 'APE-USD', 'GAL-USD'
#                  ]

cbpro_tickers = ['BTC-USDT']